services:
  nossa-casa-codigo-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'nossa-casa-codigo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - volume-nossa-casa-codigo:/Projetos/volume-nossa-casa-codigo

volumes:
  volume-nossa-casa-codigo: