services:
  nossa-casa-codigo-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DATABASE: 'casadocodigokotlin'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '123456'

    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - volume-nossa-casa-codigo:/Projetos/volume-nossa-casa-codigo

volumes:
  volume-nossa-casa-codigo: