micronaut:
  application:
    name: nossaCasaDoCodigo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/casadocodigokotlin
    driverClassName: org.postgresql.Driver
    username: user
    password: 123456
    schema-generate: CREATE_DROP

jpa.default.properties.hibernate.hbm2ddl.auto: update
spring:
  jackson:
    serialization:
      write_dates_as_timestamps=false: